// Generated by `flutterfire configure --project=foodcal-ai-app`.
// Regenerate by re-running that command from the project root if the
// Firebase project's apps change (new platform added, app deleted, etc).
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJEfsKL8CslWea3urJhWASm3DGJOtaQ8Q',
    appId: '1:520578850983:web:538809505a10bb2c79fb82',
    messagingSenderId: '520578850983',
    projectId: 'foodcal-ai-app',
    authDomain: 'foodcal-ai-app.firebaseapp.com',
    storageBucket: 'foodcal-ai-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg7YfyLjN8KcI-Jr4je3s5ZHYojc4mETU',
    appId: '1:520578850983:android:155d38d15ca4f27d79fb82',
    messagingSenderId: '520578850983',
    projectId: 'foodcal-ai-app',
    storageBucket: 'foodcal-ai-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP5QNQKk37kwNowkwcXO-zanYyze9AV3E',
    appId: '1:520578850983:ios:baf369011bb63b1e79fb82',
    messagingSenderId: '520578850983',
    projectId: 'foodcal-ai-app',
    storageBucket: 'foodcal-ai-app.firebasestorage.app',
    iosBundleId: 'com.foodcalai.foodCalorieTracker',
  );
}
